tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#e9c349",
        "surface-dim": "#121414",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "on-primary-fixed": "#241a00",
        "tertiary-fixed": "#e5e2e1",
        error: "#ffb4ab",
        "secondary-fixed": "#c3f400",
        "secondary-container": "#c3f400",
        "on-secondary-container": "#556d00",
        "surface-bright": "#37393a",
        "on-secondary-fixed-variant": "#3c4d00",
        surface: "#121414",
        "error-container": "#93000a",
        "surface-container-high": "#282a2b",
        "tertiary-container": "#b5b2b2",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-primary": "#735c00",
        "outline-variant": "#4d4635",
        "on-secondary": "#283500",
        "primary-fixed": "#ffe088",
        "secondary-fixed-dim": "#abd600",
        "primary-fixed-dim": "#e9c349",
        "on-surface": "#e2e2e2",
        "on-primary": "#3c2f00",
        "inverse-on-surface": "#2f3131",
        tertiary: "#d0cecd",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474646",
        background: "#121414",
        outline: "#99907c",
        "on-error-container": "#ffdad6",
        "surface-variant": "#333535",
        "surface-container-highest": "#333535",
        "on-tertiary-container": "#454545",
        "on-error": "#690005",
        "surface-container-low": "#1a1c1c",
        "surface-container": "#1e2020",
        "inverse-surface": "#e2e2e2",
        "on-secondary-fixed": "#161e00",
        "on-background": "#e2e2e2",
        primary: "#f2ca50",
        secondary: "#ffffff",
        "on-primary-fixed-variant": "#574500",
        "on-tertiary": "#313030",
        "surface-container-lowest": "#0c0f0f",
        "on-surface-variant": "#d0c5af",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "body-lg": ["Inter"],
        "display-lg": ["Montserrat"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "1.2",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
};
